//! Cross-language verification tests
//!
//! These tests verify that COSE_Sign1 signatures created by the TypeScript SDK
//! can be verified by the Rust core. The test fixtures are generated by running
//! the TypeScript SDK's signPoc() with a known key pair and PoC payload.
//!
//! To regenerate test fixtures, run:
//!   cd sdks/typescript && npx ts-node scripts/generate-cross-lang-fixture.ts

use provenance_core::crypto::{KeyPair as RustKeyPair, SignedPoc, PublicKey};
use base64::{Engine, engine::general_purpose::STANDARD};

fn hex_to_bytes(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

/// Verify that a PoC signed by the Rust implementation can round-trip
/// through serialization and still verify. This validates the core
/// COSE_Sign1 signing/verification pipeline that both Rust and TypeScript share.
#[test]
fn verify_cose_sign1_roundtrip() {
    use provenance_core::pca::ExecutorBinding;
    use provenance_core::poc::PocBuilder;

    let kp = RustKeyPair::generate("cross-lang-key");
    let pk = kp.public_key();

    // Build a PoC with realistic predecessor data (valid base64 when serialized)
    let poc = PocBuilder::new(b"mock-predecessor-pca-data".to_vec())
        .ops(vec!["read:*".into()])
        .executor(ExecutorBinding::new().with("service", "test"))
        .build()
        .unwrap();

    // Sign
    let signed = kp.sign_poc(&poc).unwrap();

    // Serialize to bytes and back (simulating cross-language transfer)
    let bytes = signed.to_bytes().unwrap();
    let restored = SignedPoc::from_bytes(&bytes).unwrap();

    // Verify
    let verified = pk.verify_poc(&restored).unwrap();
    assert_eq!(verified, poc);
}

/// Verify that COSE_Sign1 structures with the same format as TypeScript SDK
/// can be parsed and verified in Rust. The TypeScript SDK encodes:
/// - Protected header: {1: -8 (EdDSA), 4: kid_bytes}
/// - Payload: JSON-encoded PoC
/// - Signature: Ed25519 over Sig_structure
///
/// This test creates a known key, signs with Rust (same algorithm), and verifies
/// the COSE_Sign1 binary format is compatible.
#[test]
fn verify_known_key_signature() {
    use provenance_core::pca::ExecutorBinding;
    use provenance_core::poc::PocBuilder;

    // Use a fixed seed for deterministic key generation
    let seed: [u8; 32] = hex_to_bytes("0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef")
        .try_into()
        .unwrap();

    let kp = RustKeyPair::from_bytes("test-key", &seed).unwrap();
    let pk = kp.public_key();
    // The public key derived from this seed should be deterministic
    assert!(!pk.to_bytes().is_empty());

    // Sign a PoC
    let poc = PocBuilder::new(b"test-predecessor".to_vec())
        .ops(vec!["read:*".into()])
        .executor(ExecutorBinding::new().with("service", "test"))
        .build()
        .unwrap();

    let signed = kp.sign_poc(&poc).unwrap();
    let bytes = signed.to_bytes().unwrap();
    let b64 = STANDARD.encode(&bytes);

    // Verify we can decode from base64 (as TypeScript would send)
    let decoded_bytes = STANDARD.decode(&b64).unwrap();
    let restored = SignedPoc::from_bytes(&decoded_bytes).unwrap();
    let verified = pk.verify_poc(&restored).unwrap();
    assert_eq!(verified, poc);

    // Verify with PublicKey::from_bytes (as would happen when receiving a TS public key)
    let pk_bytes = pk.to_bytes();
    let pk_restored = PublicKey::from_bytes("test-key", &pk_bytes).unwrap();
    let verified2 = pk_restored.verify_poc(&restored).unwrap();
    assert_eq!(verified2, poc);
}
